typography_spectrum: 0.41283591385866225
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.3108512014283402
  lightness: 0.07958711326371253
  saturation: 0.33030641166474856
  rhythmicContrast: 0.01880784355334495
github: true
layout_spectrum: 0.8307486575684224
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bbbb7b19-10ab-468a-8e04-acc72556ca4e.png
name: The Foundry
url: 'http://www.revmikeumc.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: St. Matthew's UMC
    url: 'https://stmattsumc.org'
    type: external
  - name: Cherry Hill UMC
    url: 'https://cherryhillumc.org'
    type: external
  - name: My Presbyterian Friend
    url: 'https://www.danielmrose.com'
    type: external
favicon: null
title: The Foundry
content: []
description: 'Do No Harm. Do Good. Stay in Love with God. '
