typography_spectrum: 0.41283591385866225
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.3108512014283402
  lightness: 0.07958711326371253
  saturation: 0.33030641166474856
  rhythmicContrast: 0.01880784355334495
github: true
layout_spectrum: 0.8307486575684224
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bbbb7b19-10ab-468a-8e04-acc72556ca4e.png
name: The Foundry
url: 'http://www.revmikeumc.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: St. Matthew's UMC
    url: 'https://stmattsumc.org'
    type: external
  - name: Cherry Hill UMC
    url: 'https://cherryhillumc.org'
    type: external
  - name: My Presbyterian Friend
    url: 'https://www.danielmrose.com'
    type: external
favicon: null
title: The Foundry
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/749828e9-9769-49b7-97cd-8dc1a7d60492.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/749828e9-9769-49b7-97cd-8dc1a7d60492.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/51ee9c8b-d026-40a6-9c74-423eb411e0ed.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/51ee9c8b-d026-40a6-9c74-423eb411e0ed.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Do No Harm. Do Good. Stay in Love with God. '
